#!/bin/bash
GITHUB_CMD="https://github.com/JAGOANNEON1986/JAGOANNEON/raw/"
wget -O /usr/bin/badvpn "${GITHUB_CMD}main/bahan/badvpn" >/dev/null 2>&1
chmod +x /usr/bin/badvpn > /dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn1.service "${GITHUB_CMD}main/bahan/badvpn1.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn2.service "${GITHUB_CMD}main/bahan/badvpn2.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn3.service "${GITHUB_CMD}main/bahan/badvpn3.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn1.service "${GITHUB_CMD}main/bahan/badvpn4.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn2.service "${GITHUB_CMD}main/bahan/badvpn5.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn3.service "${GITHUB_CMD}main/bahan/badvpn6.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn1.service "${GITHUB_CMD}main/bahan/badvpn7.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn2.service "${GITHUB_CMD}main/bahan/badvpn8.service" >/dev/null 2>&1
wget -q -O /etc/systemd/system/badvpn3.service "${GITHUB_CMD}main/bahan/badvpn9.service" >/dev/null 2>&1
systemctl disable badvpn1.service 
systemctl stop badvpn1.service
systemctl enable badvpn1.service
systemctl start badvpn1.service 
systemctl disable badvpn2.service
systemctl stop badvpn2.service
systemctl enable badvpn2.service
systemctl start badvpn2.service
systemctl disable badvpn3.service
systemctl stop badvpn3.service
systemctl enable badvpn3.service
systemctl start badvpn3.service
systemctl disable badvpn4.service
systemctl stop badvpn4.service
systemctl enable badvpn4.service
systemctl start badvpn4.service
systemctl disable badvpn5.service
systemctl stop badvpn5.service
systemctl enable badvpn5.service
systemctl start badvpn5.service
systemctl disable badvpn6.service
systemctl stop badvpn6.service
systemctl enable badvpn6.service
systemctl start badvpn6.service
systemctl disable badvpn7.service
systemctl stop badvpn7.service
systemctl enable badvpn7.service
systemctl start badvpn7.service
systemctl disable badvpn8.service
systemctl stop badvpn8.service
systemctl enable badvpn8.service
systemctl start badvpn8.service
systemctl disable badvpn9.service
systemctl stop badvpn9.service
systemctl enable badvpn9.service
systemctl start badvpn9.service
